apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal-web
  labels:
    app: portal-web
spec:
  selector:
    matchLabels:
      app: portal-web
  template:
    metadata:
      labels:
        app: portal-web
    spec:
      containers:
        - name: portal-web
          image: portal-web-image
          ports:
            - containerPort: 4001

---
apiVersion: v1
kind: Service
metadata:
  name: portal-web
spec:
  selector:
    app: portal-web
  ports:
    - protocol: TCP
      port: 4001
